build:
  main: main.go
  binary: dptool
  goos:
    - darwin
    - linux
    - windows
  goarch:
    - amd64
    - 386
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^doco:'
      - '^typo:'
      - '^refactor'
archive:
  format_overrides:
    - goos: windows
      format: zip