build:
  main: dptool.go
  binary: dptool
  goos:
    - darwin
    - linux
    - windows
  goarch:
    - amd64
    - 386
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^refactor'
